@startuml Logic

actor user as "User"
participant logicManager as ":LogicManager"
participant appParser as ":AppParser"
participant calendarParser as ":CalendarParser"
participant showCommandParser as ":ShowCommandParser"
participant showCommand as "s:ShowCommand"
participant result as "result:Command Result"
participant model as "Model"

user -> logicManager: execute("calendar show y/2018 m/12")

@enduml